version: "3.7"
services:
  db:
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "${RDS_DB_NAME}"
      POSTGRES_PASSWORD: "${RDS_PASSWORD}"
      POSTGRES_USER: "${RDS_USERNAME}"
      PGDATA: "/var/lib/postgresql/data/tsr"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d