branch-defaults:
  default:
    environment: event-track
environment-defaults:
  event-track:
    branch: null
    repository: null
global:
  application_name: tsr
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
