branch-defaults:
  default:
    environment: event-track
global:
  application_name: tsr
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-west-2
  workspace_type: Application
