spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  flyway:
    locations: classpath:/db/migration
    ignore-missing-migrations: false
    out-of-order: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        jdbc:
          batch-size: 1000
          order_inserts: true
          order_updates: true
        create_empty_composites:
          enabled: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: 24h
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    time-zone: UTC
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: tsr_keycloak
            clientSecret: random-password
        provider:
          keycloak:
            issuer-uri: ${TSR_KEYCLOAK_HOST}/auth/realms/tsr
      resourceserver:
        jwt:
          jwk-set-uri: ${TSR_KEYCLOAK_HOST}/auth/realms/tsr/protocol/openid-connect/certs
logging:
  level:
    events:
      tracked:
        DEBUG
    org:
      flywaydb: TRACE
      hibernate:
        SQL: OFF
        type: OFF
      springframework:
        web: INFO
        ws:
          server:
            MessageTracing:
              send: off
              recevied: off