spring:
  datasource:
    url: ${RDS_JDBC_DATABASE_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  flyway:
    locations: classpath:/db/migration
    ignore-missing-migrations: false
    out-of-order: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch-size: 1000
          order_inserts: true
          order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: 24h
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: tsr_keycloak
            clientSecret: ${TSR_KEYCLOAK_SECRET_KEY}
            scope: openid,profile
        provider:
          keycloak:
            issuer-uri: ${TSR_KEYCLOAK_HOST}/auth/realms/tsr
      resourceserver:
        jwt:
          jwk-set-uri: ${TSR_KEYCLOAK_HOST}/auth/realms/tsr/protocol/openid-connect/certs

logging:
  level:
    events:
      tracked:
        DEBUG
    org:
      flywaydb: TRACE
      hibernate:
        SQL: OFF
        type: OFF
      springframework:
        security: error
        web: INFO
        ws:
          server:
            MessageTracing:
              send: off
              recevied: off


#Sets all session cookies to HttpOnly and to Secure in the browser
#STIG ID: APSC-DV-002220, STIG ID: APSC-DV-002210
server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
      tracking-modes: COOKIE
  forward-headers-strategy: native
