ALTER TABLE organization ADD COLUMN created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE organization ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE organization ADD COLUMN last_modified_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE organization ADD COLUMN last_modified_by VARCHAR(255) NOT NULL DEFAULT '';