ALTER TABLE event ALTER COLUMN start_date TYPE TIMESTAMPTZ;
ALTER TABLE event ALTER COLUMN end_date TYPE TIMESTAMPTZ;
ALTER TABLE event ALTER COLUMN created_date TYPE TIMESTAMPTZ;
ALTER TABLE event ALTER COLUMN last_modified_date TYPE TIMESTAMPTZ;