CREATE TABLE resourcer (
    user_id BIGINT REFERENCES tsr_user (id) ON UPDATE CASCADE ON DELETE CASCADE,
    organization_id BIGINT REFERENCES organization (organization_id) ON UPDATE CASCADE ON DELETE CASCADE,
    event_task_category_id BIGINT REFERENCES event_task_category (event_task_category_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT resourcer_pkey PRIMARY KEY (user_id, organization_id, event_task_category_id)
);

ALTER TABLE event_task
    DROP COLUMN resourcer_id;

DELETE FROM organization;

INSERT INTO organization (organization_name, organization_display_name, sort_order) VALUES ('2_75', '2/75', 1);
INSERT INTO organization (organization_name, organization_display_name, sort_order) VALUES ('A_2_75', 'A Co, 2/75', 2);
INSERT INTO organization (organization_name, organization_display_name, sort_order) VALUES ('B_2_75', 'B Co, 2/75', 3);
INSERT INTO organization (organization_name, organization_display_name, sort_order) VALUES ('C_2_75', 'C Co, 2/75', 4);
INSERT INTO organization (organization_name, organization_display_name, sort_order) VALUES ('D_2_75', 'D Co, 2/75', 5);
INSERT INTO organization (organization_name, organization_display_name, sort_order) VALUES ('E_2_75', 'E Co, 2/75', 6);

ALTER TABLE event_task_category
    DROP COLUMN event_task_category_id CASCADE;

DELETE FROM event_task_category;

ALTER TABLE event_task_category
    ADD COLUMN event_task_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_ONE', 'Class I - Subsistence');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_TWO', 'Class II - Supplies');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_THREE', 'Class III - Fuels');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_FOUR', 'Class IV - Construction');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_FIVE', 'Class V - Ammunition');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_SEVEN', 'Class VII - Major End Items');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_EIGHT', 'Class VIII - Medical');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_NINE', 'Class IX - Repair Parts');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('CLASS_TEN', 'Class X - Other Equipment');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('LAND', 'Land');
INSERT INTO event_task_category (event_task_name, event_task_display_name) VALUES ('MWR', 'MWR');

DELETE FROM event_type;

INSERT INTO event_type (event_type_name, display_name, sort_order) VALUES ('FLAT_RANGE', 'flat range', 1);
INSERT INTO event_type (event_type_name, display_name, sort_order) VALUES ('MANEUVER_LFX', 'maneuver live fire exercise', 2);
INSERT INTO event_type (event_type_name, display_name, sort_order) VALUES ('MANEUVER', 'maneuver range', 3);
INSERT INTO event_type (event_type_name, display_name, sort_order) VALUES ('UNCATEGORIZED', 'other', 4);