FROM openjdk:17-alpine

LABEL "name"="Backend Gradle Test"
LABEL "maintainer"="Kyle Gorak"
LABEL "version"="0.0.1"

LABEL "com.github.actions.name"="Backend Gradle Test"
LABEL "com.github.actions.description"="Backend Gradle Test"
LABEL "com.github.actions.icon"="terminal"
LABEL "com.github.actions.color"="green"

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
