# This is a basic workflow to help you get started with Actions

name: Branch-Test CI/CD

on:
  push:
    branches-ignore: [ master ]

jobs:
  test:
    name: run-tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-frontend
      - uses: ./.github/actions/test-backend