name: Full CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Jar
        run: ./build.sh

      - name: Saves build artifact
        uses: actions/upload-artifact@v2
        with:
          name: tsr-jar
          path: build/libs/*.jar
  test:
    name: run tests
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-frontend
      - uses: ./.github/actions/test-backend
  docker:
    name: push to docker
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: download build aritifact
        uses: actions/download-artifact@v2
        with:
          name: tsr-jar
          path: $GITHUB_WORKSPACE/tsr.jar
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: g0rak/tsr
          tag_with_ref: true
          dockerfile: $GITHUB_WORKSPACE/pipeline/docker/app_container/Dockerfile
  deploy_aws:
    name: deploy to aws eb
    runs-on: ubuntu-18.04
    needs: docker
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to AWS EB
        uses: ./.github/actions/deploy-eb
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2