name: Full CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build Jar
        run: ./build.sh

      - name: Saves build artifact
        uses: actions/upload-artifact@v2
        with:
          name: tsr-jar
          path: build/libs/*.jar
  test:
    name: run tests
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-frontend
      - uses: ./.github/actions/test-backend
  deploy_aws:
    name: deploy to aws eb
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: download build aritifact
        uses: actions/download-artifact@v2
        with:
          name: tsr-jar
          path: pipeline/eb/tsr

      - name: Deploy to AWS EB
        uses: ./.github/actions/deploy-eb
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
          SHA8: ${{ env.GITHUB_SHA }}